# Generated by Django 4.2.7 on 2026-02-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(default=1)),
                ('post_held', models.CharField(max_length=200, verbose_name='Name of Post Held')),
                ('organization', models.CharField(max_length=300, verbose_name='Name of Organization')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Experience in Years')),
                ('experience_months', models.PositiveIntegerField(default=0, verbose_name='Experience in Months')),
                ('job_type', models.CharField(max_length=100, verbose_name='Type/Nature of Job')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employment Detail',
                'verbose_name_plural': 'Employment Details',
                'ordering': ['sr_no'],
            },
        ),
    ]
