# Generated by Django 4.2.7 on 2026-02-26 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_passed', models.CharField(choices=[('matric', 'Matric'), ('10+2', '10+2'), ('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('mphil', 'M.Phil.'), ('net_jrf_gate_gpat', 'NET/JRF/GATE/GPAT'), ('fellowship', 'Any Other Fellowship'), ('other', 'Any Other Qualification')], max_length=50, verbose_name='Examination Passed')),
                ('custom_examination', models.CharField(blank=True, max_length=200, null=True, verbose_name='Custom Examination Name')),
                ('university_board', models.CharField(max_length=300, verbose_name='Name of University / Board')),
                ('year_of_passing', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)], verbose_name='Year of Passing')),
                ('roll_number', models.CharField(max_length=50, verbose_name='Roll No.')),
                ('grade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Grade')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Marks Obtained')),
                ('max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Maximum Marks')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage of Marks')),
                ('subjects', models.CharField(max_length=500, verbose_name='Subjects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Qualification',
                'verbose_name_plural': 'Academic Qualifications',
                'ordering': ['-year_of_passing'],
            },
        ),
    ]
