# Generated by Django 4.2.7 on 2026-02-26 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(max_length=100, verbose_name="Mother's Name")),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], max_length=3, verbose_name='Category')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^\\d{10}$')], verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('address_line1', models.CharField(max_length=200, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pincode')),
                ('program_applied', models.CharField(choices=[('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('MBA', 'MBA'), ('PHD', 'PhD'), ('BSC', 'B.Sc'), ('MSC', 'M.Sc'), ('BCOM', 'B.Com'), ('MCOM', 'M.Com')], max_length=5, verbose_name='Program Applied')),
                ('last_school', models.CharField(max_length=200, verbose_name='Last School/College Attended')),
                ('board_university', models.CharField(max_length=200, verbose_name='Board/University')),
                ('year_of_passing', models.IntegerField(verbose_name='Year of Passing')),
                ('percentage_marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage Marks')),
                ('photo', models.ImageField(upload_to='admission_photos/', verbose_name='Passport Size Photo')),
                ('signature', models.ImageField(upload_to='admission_signatures/', verbose_name='Signature')),
                ('achievements', models.TextField(blank=True, verbose_name='Achievements and Extracurricular Activities')),
                ('declaration', models.BooleanField(default=False, verbose_name='I declare that all information provided is true')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University Admission',
                'verbose_name_plural': 'University Admissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
