# Generated by Django 4.2.7 on 2026-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
