# Generated by Django 4.2.7 on 2026-02-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0002_personaldetail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
