# Generated by Django 4.2.7 on 2026-02-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0005_alter_personaldetail_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='emergency_contact_relation',
        ),
    ]
