# Generated by Django 4.2.7 on 2026-02-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0006_remove_personaldetail_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='alternate_email',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='blood_group',
        ),
    ]
