# Generated by Django 4.2.7 on 2026-02-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0007_remove_personaldetail_alternate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
