# Generated by Django 4.2.16 on 2026-02-26 11:34

from django.db import migrations, models
import django.db.models.deletion
import master_control.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Advertisement Title')),
                ('description', models.TextField(blank=True, help_text='Brief description of the advertisement', verbose_name='Description')),
                ('image', models.ImageField(help_text='Upload banner/image (Recommended: 1920x600px for banners)', upload_to=master_control.models.upload_path, verbose_name='Advertisement Image')),
                ('redirect_url', models.URLField(blank=True, help_text='URL to redirect when clicked', verbose_name='Redirect URL')),
                ('display_type', models.CharField(choices=[('banner', 'Banner'), ('sidebar', 'Sidebar'), ('notice', 'Notice')], default='banner', help_text='Where to display this advertisement', max_length=20, verbose_name='Display Type')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower number = displayed first', verbose_name='Priority')),
                ('start_date', models.DateField(help_text='Date when advertisement becomes visible', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Date when advertisement expires', verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('course_name', models.CharField(db_index=True, help_text='Name of the academic program', max_length=255, verbose_name='Course Name')),
                ('department_name', models.CharField(help_text='Department offering this course', max_length=255, verbose_name='Department')),
                ('degree_type', models.CharField(help_text='e.g., B.Tech, M.Sc, Ph.D', max_length=100, verbose_name='Degree Type')),
                ('duration_years', models.PositiveIntegerField(help_text='Program duration in years', verbose_name='Duration (Years)')),
                ('total_seats', models.PositiveIntegerField(help_text='Total available seats for this course', verbose_name='Total Seats')),
                ('display_priority', models.PositiveIntegerField(default=0, help_text='Lower number = appears first on frontend', verbose_name='Display Priority')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['display_priority', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('portal_name', models.CharField(help_text='Name of the university admission portal', max_length=255, verbose_name='Portal Name')),
                ('current_academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20, verbose_name='Current Academic Year')),
                ('is_portal_active', models.BooleanField(default=True, help_text='Whether the portal is accessible to users', verbose_name='Portal Active')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When enabled, portal shows maintenance message', verbose_name='Maintenance Mode')),
                ('application_start_date', models.DateField(verbose_name='Application Start Date')),
                ('application_end_date', models.DateField(verbose_name='Application End Date')),
                ('contact_email', models.EmailField(help_text='Support email displayed on the portal', max_length=254, verbose_name='Contact Email')),
                ('support_phone', models.CharField(help_text='Support phone number displayed on the portal', max_length=20, verbose_name='Support Phone')),
            ],
            options={
                'verbose_name': 'Portal Setting',
                'verbose_name_plural': 'Portal Settings',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Notice Title')),
                ('content', models.TextField(help_text='Full notice text', verbose_name='Notice Content')),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF, DOC, or image attachment', null=True, upload_to=master_control.models.upload_path, verbose_name='Attachment')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower number = displayed first on homepage', verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['priority', 'is_active'], name='master_cont_priorit_b4f90f_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomepageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(help_text='Main headline for the slider', max_length=255, verbose_name='Slider Title')),
                ('subtitle', models.CharField(blank=True, help_text='Supporting text below the title', max_length=255, verbose_name='Subtitle')),
                ('image', models.ImageField(help_text='Upload slider image (Recommended: 1920x600px)', upload_to=master_control.models.upload_path, verbose_name='Slider Image')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Display order - lower number appears first', verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Homepage Slider',
                'verbose_name_plural': 'Homepage Sliders',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['priority', 'is_active'], name='master_cont_priorit_08cf11_idx')],
            },
        ),
        migrations.CreateModel(
            name='FormConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_form_open', models.BooleanField(default=False, help_text='Whether applications are currently being accepted', verbose_name='Form Open')),
                ('is_payment_required', models.BooleanField(default=True, help_text='Whether application fee payment is mandatory', verbose_name='Payment Required')),
                ('application_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee amount in INR', max_digits=10, verbose_name='Application Fee (₹)')),
                ('max_applications_allowed', models.PositiveIntegerField(default=100, help_text='Maximum number of applications to accept', verbose_name='Max Applications')),
                ('form_start_date', models.DateField(blank=True, help_text='Date when form opens for applications', null=True, verbose_name='Form Start Date')),
                ('form_end_date', models.DateField(blank=True, help_text='Date when form closes for applications', null=True, verbose_name='Form End Date')),
                ('course', models.ForeignKey(help_text='Course this form configuration applies to', on_delete=django.db.models.deletion.CASCADE, related_name='form_configs', to='master_control.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Form Configuration',
                'verbose_name_plural': 'Form Configurations',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name', 'is_active'], name='master_cont_course__29666a_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department_name', 'is_active'], name='master_cont_departm_4cd645_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['priority', 'is_active', 'display_type'], name='master_cont_priorit_f4e561_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['start_date', 'end_date', 'is_active'], name='master_cont_start_d_cd2cf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formconfiguration',
            unique_together={('course',)},
        ),
    ]
