# Generated by Django 4.2.16 on 2026-02-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='file',
            field=models.FileField(blank=True, help_text='Upload advertisement file (PDF recommended for best results)', null=True, upload_to='advertisements/', verbose_name='Advertisement File'),
        ),
    ]
