# Generated by Django 4.2.16 on 2026-02-27 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import master_control.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_control', '0002_remove_advertisement_image_advertisement_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('application_no', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('payment_pending', 'Payment Pending'), ('payment_success', 'Payment Success'), ('under_review', 'Under Review'), ('admitted', 'Admitted'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=30)),
                ('is_data_locked', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='master_control.advertisement')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='master_control.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('label', models.CharField(max_length=255)),
                ('name', models.SlugField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('boolean', 'Boolean'), ('file', 'File')], default='text', max_length=20)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('conditional_field_name', models.SlugField(blank=True, max_length=80, null=True)),
                ('conditional_operator', models.CharField(blank=True, choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('in', 'In'), ('not_in', 'Not In'), ('exists', 'Exists'), ('not_exists', 'Not Exists')], max_length=20, null=True)),
                ('conditional_value', models.CharField(blank=True, max_length=255, null=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='master_control.advertisement')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_fields', to='master_control.course')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='master_control.advertisementfield')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_courses', to='master_control.advertisement')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_courses', to='master_control.course')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('field_snapshot', models.JSONField(default=dict)),
                ('value_text', models.TextField(blank=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to=master_control.models.upload_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='master_control.admissionapplication')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_values', to='master_control.advertisementfield')),
            ],
            options={
                'indexes': [models.Index(fields=['application', 'field'], name='master_cont_applica_79ffd1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='applicationfieldvalue',
            constraint=models.UniqueConstraint(fields=('application', 'field'), name='uniq_application_field_value'),
        ),
        migrations.AddIndex(
            model_name='advertisementfieldoption',
            index=models.Index(fields=['field', 'display_order'], name='master_cont_field_i_7e72bb_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisementfield',
            index=models.Index(fields=['advertisement', 'course', 'is_active'], name='master_cont_adverti_72091a_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisementfield',
            index=models.Index(fields=['advertisement', 'display_order'], name='master_cont_adverti_e58aa5_idx'),
        ),
        migrations.AddConstraint(
            model_name='advertisementfield',
            constraint=models.UniqueConstraint(fields=('advertisement', 'name'), name='uniq_advertisement_field_name'),
        ),
        migrations.AddIndex(
            model_name='advertisementcourse',
            index=models.Index(fields=['advertisement', 'course', 'is_active'], name='master_cont_adverti_72d7b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='advertisementcourse',
            unique_together={('advertisement', 'course')},
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['student', 'status'], name='master_cont_student_6f61ab_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['advertisement', 'course'], name='master_cont_adverti_a78c42_idx'),
        ),
    ]
