# Generated by Django 4.2.16 on 2026-02-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0003_admissionapplication_advertisementfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='department_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ApplicationProfileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('father_name', models.CharField(blank=True, default='', max_length=255)),
                ('mother_name', models.CharField(blank=True, default='', max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('aadhar_no', models.CharField(blank=True, default='', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('address', models.TextField(blank=True, default='')),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_snapshot', to='master_control.admissionapplication')),
            ],
            options={
                'verbose_name': 'Application Profile Snapshot',
                'verbose_name_plural': 'Application Profile Snapshots',
            },
        ),
        migrations.CreateModel(
            name='ApplicationExperienceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('experience_type', models.CharField(blank=True, default='', max_length=100)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_snapshots', to='master_control.admissionapplication')),
            ],
            options={
                'verbose_name': 'Application Experience Snapshot',
                'verbose_name_plural': 'Application Experience Snapshots',
                'indexes': [models.Index(fields=['application', 'snapshot_created_at'], name='master_cont_applica_c24c6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEducationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('board_university', models.CharField(blank=True, default='', max_length=255)),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('passing_year', models.CharField(blank=True, default='', max_length=10)),
                ('percentage', models.CharField(blank=True, default='', max_length=20)),
                ('cgpa', models.CharField(blank=True, default='', max_length=20)),
                ('subjects', models.TextField(blank=True, default='')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_snapshots', to='master_control.admissionapplication')),
            ],
            options={
                'verbose_name': 'Application Education Snapshot',
                'verbose_name_plural': 'Application Education Snapshots',
                'indexes': [models.Index(fields=['application', 'snapshot_created_at'], name='master_cont_applica_37863a_idx')],
            },
        ),
    ]
