# Generated by Django 4.2.7 on 2026-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0004_admissionapplication_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationeducationsnapshot',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
