# Generated by Django 4.2.7 on 2026-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0005_applicationeducationsnapshot_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationexperiencesnapshot',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
