# Generated by Django 4.2.7 on 2026-02-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0006_applicationexperiencesnapshot_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='category_other',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='category_tick',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='corr_address_block',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='email_correspondence',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='emp_post_current',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='employed_status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='fellowship_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='fellowship_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='job_nature',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='mobile_telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='org_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='org_telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='organization_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='organization_name_current',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='other_class',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='other_institution',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='other_result',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='other_session',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='proposed_supervisor',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='publications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='pursuing_other_course',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='research_experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='service_period',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationprofilesnapshot',
            name='specialization_area',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='applicationprofilesnapshot',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_snapshots', to='master_control.admissionapplication'),
        ),
        migrations.AlterField(
            model_name='applicationprofilesnapshot',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationprofilesnapshot',
            name='district',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationprofilesnapshot',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationprofilesnapshot',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='applicationprofilesnapshot',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationprofilesnapshot',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
