# Generated by Django 4.2.7 on 2026-02-27 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_control', '0007_applicationprofilesnapshot_category_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='academic_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores all academic qualifications as JSON'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='category_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='category_tick',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='corr_address_block',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='email_correspondence',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='emp_post_current',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='employed_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='employment_history',
            field=models.JSONField(blank=True, default=dict, help_text='Stores all employment history as JSON'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='fellowship_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='fellowship_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='is_printed',
            field=models.BooleanField(default=False, help_text='Mark if application has been printed'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='job_nature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mobile_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='org_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='org_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='organization_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='organization_name_current',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='other_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='other_institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='other_result',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='other_session',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/photos/'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='printed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='proposed_supervisor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='publications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='pursuing_other_course',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='research_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='service_period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='applications/signatures/'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='specialization_area',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['application_no'], name='master_cont_applica_59e865_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['-created_at'], name='master_cont_created_041c04_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['category'], name='master_cont_categor_4e67c0_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionapplication',
            index=models.Index(fields=['is_printed'], name='master_cont_is_prin_1dac0b_idx'),
        ),
    ]
