# Generated by Django 4.2.7 on 2026-02-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0008_admissionapplication_aadhar_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortalSettings',
        ),
    ]
