# Generated by Django 4.2.7 on 2026-02-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0009_delete_portalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('portal_name', models.CharField(help_text='Name of the university admission portal', max_length=255, verbose_name='Portal Name')),
                ('current_academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20, verbose_name='Current Academic Year')),
                ('is_portal_active', models.BooleanField(default=True, help_text='Whether the portal is accessible to users', verbose_name='Portal Active')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When enabled, portal shows maintenance message', verbose_name='Maintenance Mode')),
                ('application_start_date', models.DateField(verbose_name='Application Start Date')),
                ('application_end_date', models.DateField(verbose_name='Application End Date')),
                ('contact_email', models.EmailField(help_text='Support email displayed on the portal', max_length=254, verbose_name='Contact Email')),
                ('support_phone', models.CharField(help_text='Support phone number displayed on the portal', max_length=20, verbose_name='Support Phone')),
            ],
            options={
                'verbose_name': 'Portal Setting',
                'verbose_name_plural': 'Portal Settings',
            },
        ),
    ]
