# Generated by Django 4.2.7 on 2026-02-27 16:16

from django.db import migrations, models
import master_control_project.master_control.models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0010_portalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='ugc_category',
            field=models.CharField(blank=True, choices=[('Category I (JRF)', 'Category I (JRF)'), ('Category II (NET)', 'Category II (NET)'), ('Category III (Ph.D. Only)', 'Category III (Ph.D. Only)'), ('Not Applicable', 'Not Applicable')], help_text='UGC category as per NET entrance test notification', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file',
            field=models.FileField(blank=True, help_text='Upload advertisement file (PDF recommended for best results)', null=True, upload_to=master_control_project.master_control.models.upload_path, verbose_name='Advertisement File'),
        ),
        migrations.AlterField(
            model_name='applicationeducationsnapshot',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=master_control_project.master_control.models.upload_path),
        ),
        migrations.AlterField(
            model_name='applicationexperiencesnapshot',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=master_control_project.master_control.models.upload_path),
        ),
        migrations.AlterField(
            model_name='applicationfieldvalue',
            name='value_file',
            field=models.FileField(blank=True, null=True, upload_to=master_control_project.master_control.models.upload_path),
        ),
        migrations.AlterField(
            model_name='applicationprofilesnapshot',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=master_control_project.master_control.models.upload_path),
        ),
        migrations.AlterField(
            model_name='applicationprofilesnapshot',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=master_control_project.master_control.models.upload_path),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='image',
            field=models.ImageField(help_text='Upload slider image (Recommended: 1920x600px)', upload_to=master_control_project.master_control.models.upload_path, verbose_name='Slider Image'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional PDF, DOC, or image attachment', null=True, upload_to=master_control_project.master_control.models.upload_path, verbose_name='Attachment'),
        ),
    ]
