# Generated by Django 4.2.7 on 2026-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0011_admissionapplication_ugc_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Payment Amount (₹)'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('cash', 'Cash'), ('dd', 'Demand Draft'), ('cheque', 'Cheque')], max_length=50, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_remarks',
            field=models.TextField(blank=True, verbose_name='Payment Remarks'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Transaction ID'),
        ),
    ]
