# Generated by Django 4.2.7 on 2026-02-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0012_admissionapplication_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='payment_remarks',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Transaction Date'),
        ),
    ]
