# Generated by Django 4.2.7 on 2026-02-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0013_remove_admissionapplication_payment_amount_and_more'),
    ]

    operations = [
    ]
