# Generated by Django 5.2.5 on 2026-02-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0014_auto_20260227_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment transaction ID', max_length=100, verbose_name='Payment ID'),
        ),
    ]
