# Generated by Django 6.0.2 on 2026-02-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0015_add_payment_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='payment_transaction_id',
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date when payment was made', null=True, verbose_name='Payment Date'),
        ),
    ]
