# Generated by Django 5.2.5 on 2026-02-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0016_remove_admissionapplication_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='ugc_validity_date',
            field=models.DateField(blank=True, help_text='UGC validity date for Category I, II, III', null=True),
        ),
    ]
