# Generated by Django 5.2.5 on 2026-02-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0017_admissionapplication_ugc_validity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='ugc_validity_date',
        ),
    ]
