# Generated by Django 5.2.5 on 2026-02-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0018_remove_admissionapplication_ugc_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='ugc_validity_date',
            field=models.DateField(blank=True, help_text='UGC validity date for NET/JRF certificate', null=True),
        ),
    ]
