# Generated by Django 5.2.5 on 2026-02-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0019_admissionapplication_ugc_validity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='apply_course',
            field=models.CharField(blank=True, choices=[('Ph.D.', 'Ph.D.'), ('PGDRP', 'PGDRP')], help_text='Select course to apply for', max_length=50),
        ),
    ]
