# Generated by Django 5.2.5 on 2026-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0020_admissionapplication_apply_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='department',
            field=models.CharField(blank=True, choices=[('Physical Education', 'Physical Education'), ('Zoology', 'Zoology'), ('Commerce', 'Commerce'), ('Biotechnology', 'Biotechnology'), ('Physics', 'Physics'), ('Pharmaceutical', 'Pharmaceutical'), ('Psychology', 'Psychology'), ('History', 'History'), ('Chemistry', 'Chemistry'), ('Management', 'Management'), ('Math', 'Math'), ('English', 'English')], help_text='Select department for Ph.D. program', max_length=100),
        ),
    ]
