# Generated by Django 5.2.5 on 2026-02-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0021_admissionapplication_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='study_mode',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], help_text='Select study mode for Ph.D. program', max_length=20),
        ),
    ]
