# Generated by Django 4.2.7 on 2026-03-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0022_admissionapplication_study_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='category_certificate',
            field=models.FileField(blank=True, help_text='SC/ST/BC/EWS/SBC/PwD/ESM/Others certificate in Govt. format', null=True, upload_to='applications/documents/category/', verbose_name='Category Certificate (SOP-VI to SOP-XI)'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='character_certificate',
            field=models.FileField(blank=True, help_text='Required if there is gap in study', null=True, upload_to='applications/documents/character/', verbose_name='Character Certificate (SOP-V)'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='father_guardian_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/father_guardian/', verbose_name='Certificate from Father/Guardian (SOP-III)'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='haryana_domicile_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/domicile/', verbose_name='Haryana Domicile Certificate'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='migration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/migration/', verbose_name='Migration Certificate'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='no_objection_certificate',
            field=models.FileField(blank=True, help_text='Required for employed candidates', null=True, upload_to='applications/documents/no_objection/', verbose_name='No Objection cum Service Certificate (SOP-II)'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='nri_declaration',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/nri/', verbose_name='NRI/Foreign Citizen Declaration (SOP-XII)'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='parent_guardian_affidavit',
            field=models.FileField(blank=True, help_text='Attested by executive magistrate/oath commissioner/notary public', null=True, upload_to='applications/documents/affidavit/', verbose_name='Affidavit of Parent/Guardian (SOP-IV)'),
        ),
    ]
