# Generated by Django 4.2.7 on 2026-03-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_control', '0023_admissionapplication_category_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='graduation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/certificates/graduation/', verbose_name='Graduation Certificate'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='other_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/certificates/other/', verbose_name='Other Certificate'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='post_graduation_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/certificates/post_graduation/', verbose_name='Post Graduation Certificate'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='tenth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/certificates/tenth/', verbose_name='10th Certificate'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='twelfth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/certificates/twelfth/', verbose_name='12th Certificate'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='ugc_csir_jrf_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/certificates/ugc_csir_jrf/', verbose_name='UGC/CSIR JRF Certificate'),
        ),
    ]
